name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  merge_group:
    branches:
      - main

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: fmt
        run: cargo +nightly fmt --all -- --check

      - uses: dtolnay/rust-toolchain@stable
      - name: build
        run: cargo build

      - name: clippy
        run: cargo clippy --workspace

      - name: test on Stable
        run: cargo test --workspace

      - name: Tests with rawtext hack
        run: cargo test -p rstml --features "rawtext-stable-hack-module"

      - name: Test extendable feature in rstml-control-flow
        run: cargo test -p rstml-control-flow --features "extendable"

      - uses: dtolnay/rust-toolchain@nightly

      - name: test on Nightly
        run: cargo test --workspace 
